const express=require('express')
const router=express.Router()
const userController=require('../Controllers/userController')
const propertyController=require('../Controllers/propertyController')
const jwtmiddle=require('../Middleware/jwtMiddleware')
const multerMiddle=require('../Middleware/multiMiddleware')

router.post('/register',userController.userRegister)
router.post('/login',userController.userLogin)
router.post('/add-property',jwtmiddle,multerMiddle.single('image'), propertyController.addProperty)
router.get('/get-property',propertyController.getProperty)
router.get('/other-property',jwtmiddle,propertyController.getOtherProperty)
router.get('/user-property',jwtmiddle,propertyController.userProperty)
router.put('/edit-property/:pid',jwtmiddle,propertyController.editProperty)
router.delete('/remove-property/:pid',jwtmiddle,propertyController.removeProperty)
router.post('/seller',jwtmiddle,userController.sellerData)
router.post('/mail',jwtmiddle,userController.mail)
router.put('/like',jwtmiddle,propertyController.like)
module.exports=router
